### ISSUE TITLE
Wifi not working on Surface Go 1 LTE/Wifi

### ISSUE THREAD

**Issue by kevin-fibich** [linux-surface/ath10k-firmware-override#3]
The LTE version of Surface Go 1 wifi card has a different subsystem device id (3371) to the Wifi only variant (3370) of the Surface Go 1.

Manually extracting the 3370 board.bin and loading that into ath10k_core via override_board however seems to work.

To fix this issue, another entry should be added to board-2.bin for subsystem device id 3371.

This issue makes the firmware override package relevant again, since upstream also does not contain 3371.

**Comment by kevin-fibich** [comment]
Update:

just using the 3370 board.bin embedded to board-2.bin does not seem to work (no idea why).

However, rebooting into windows and looking at the driver i found the correct bin (eeprom_ar6320_3p0_TX8_lte_clpc.bin).
Adding that to board-2.bin (or board-2-surface.bin) then worked fine.

**Comment by qzed** [comment]
Thanks for reporting! Could you open a PR with the updated board-2.bin file? You should also submit that upstream (see e.g. https://github.com/linux-surface/linux-surface/issues/542).

**Comment by kevin-fibich** [comment]
PR is open (https://github.com/linux-surface/ath10k-firmware-override/pull/4)

I've built the rpm in the meantime and it works well on fedora silverblue 36.

Will try to submit board eeprom to linux-firmware later.

**Comment by qzed** [comment]
Thanks! I'll add a new release and push it to the repos.

**Comment by qzed** [comment]
The updated package should be available in the repo now (or in the next ~10 minutes).

**Comment by kevin-fibich** [comment]
Thanks a lot!

Request to include boardfile has been sent to ath10k-firmware mailing list. 
http://lists.infradead.org/pipermail/ath10k/2022-June/013691.html
